
# Ch 8 

## Prime charts



## GAM {#GAM}

*Stuff based on Morton et al. book here*  


## OC Curves

**Not a great example but it works.**  

```{r ocs}
dfw_sampled = dfw %>% group_by(months) %>% sample_n(size = 10)
dfw_groups = qcc.groups(dfw_sampled$waits, as.numeric(dfw_sampled$months))
dfw_oc = oc.curves(qcc(dfw_groups, type="xbar"))
ARL = 1/( 1 - dfw_oc[rownames(dfw_oc) == "1", 1])
```

Average run length (ARL) is `r ARL`.  



## Pareto charts


# Ch 9

# Is there a difference? {#advanced}

Too many leaders and clinicians got only one or two stats classes in their background, and as a result are tediously tied to the ritual of Statistical Hypothesis Inference Testing (more commonly known as frequentism, but this has a better acronym).  

This slavish devotion has harmed and even killed people.  


## *Is there a difference?* is not SPC

SPC methods do *not* tell you whether there is a statisically-signifianct difference between two segments of a time series. Even if it did, it's a trivial answer to the wrong question.   

What SPC does. 

What "difference" testing does. Example of brain surgery can go here.  

## Changepoint analysis {#changepoint}

Vanco orders example can go here.  

Show examples from all three packages? strucchange, bcp, and changepoint?  
